######################################################################################################################################################################

########   ##        ##     ##   #####     ####  ##    ##       ########   ##      ##       ##        ########   #######   ##    ##        ##        ########  #######
##     ##  ##        ##     ##  ##    ##    ##   ###   ##       ##     ##   ##    ##        ##        ##        ##     ##  ###   ##        ##        ##     ## #     #
##     ##  ##        ##     ##  ##          ##   ####  ##       ##     ##    ##  ##         ##        ##        ##     ##  ####  ##        ##        ##     ## #     #
########   ##        ##     ##  ##   ####   ##   ## ## ##       ########       ##           ##        ######    ##     ##  ## ## ##        ##        ########  #######
##         ##        ##     ##  ##    ##    ##   ##  ####       ##     ##     ##            ##        ##        ##     ##  ##  ####        ##        ##              #
##         ##        ##     ##  ##    ##    ##   ##   ###       ##     ##    ##             ##        ##        ##     ##  ##   ###        ##        ##              #
##         ########   #######    ######    ####  ##    ##       ########    ##              ########  ########   #######   ##    ## ###### ########  ##        ######

######################################################################################################################################################################

# This is the Size of the main Inventory
inventorySize: 45

# This is the Particle around the Crate
Particle: CRIT

# How long the Opening Crate is spinning
SpinTime: 450

# How fast the Spinning Crate Decelerate
DecelerateSpeed: 0.255

# Only turn this on if you have Votifer installed!
UseVotifer: false
# This is the Command that will be send when the Player votes
VoteRewards:
  - give %player% minecraft:diamond 1
  - cc admin keys give %player% Default2 1