######################################################################################################################################################################

########   ##        ##     ##   #####     ####  ##    ##       ########   ##      ##       ##        ########   #######   ##    ##        ##        ########  #######
##     ##  ##        ##     ##  ##    ##    ##   ###   ##       ##     ##   ##    ##        ##        ##        ##     ##  ###   ##        ##        ##     ## #     #
##     ##  ##        ##     ##  ##          ##   ####  ##       ##     ##    ##  ##         ##        ##        ##     ##  ####  ##        ##        ##     ## #     #
########   ##        ##     ##  ##   ####   ##   ## ## ##       ########       ##           ##        ######    ##     ##  ## ## ##        ##        ########  #######
##         ##        ##     ##  ##    ##    ##   ##  ####       ##     ##     ##            ##        ##        ##     ##  ##  ####        ##        ##              #
##         ##        ##     ##  ##    ##    ##   ##   ###       ##     ##    ##             ##        ##        ##     ##  ##   ###        ##        ##              #
##         ########   #######    ######    ####  ##    ##       ########    ##              ########  ########   #######   ##    ## ###### ########  ##        ######

######################################################################################################################################################################

# This is the Size of the main Inventory
inventorySize: 45

# This is the Particle around the Crate
Particle: CRIT

# How long the Opening Crate is spinning
SpinTime: 450

# How fast the Spinning Crate Decelerate
DecelerateSpeed: 0.255

# Only turn this on if you have Votifer installed!
UseVotifer: false
# This is the Command that will be send when the Player votes
VoteRewards:
  - 'give %player% minecraft:diamond 1'
  - 'cc admin keys give %player% Default2 1'

# Show in Crate Preview that the Item ist a CommandReward
CommandRewardPreview: true

CommandRewardLores:
  - '&7&m-----------------'
  - '&e&lCommand Reward'
  - '&7&m-----------------'

# ####
# ####
# ####
# #### Add commands Ingame with /cc item addCommand <Command>
# #### All commands that are executed as Console.
# #### You can use %player% to get the PlayerName.
# #### You can use the sudo command (from Essentials)
#      to execute the command as the Player
# ####
# ####
# ####

defaultProbability: 100.0

tickSound: 'block.note_block.pling'
giveSound: 'entity.player.levelup'

mysql: false
host: 'localhost'
port: 3306
database: 'CompactCrates'
username: 'root'
password: 'password'
table: 'CompactCrates'